<footer id="site-footer" class="site-footer">
  <div class="site-container  width-padding">
    <div class="footer-img-logo">
      <img src="theme/images/tmp/img-footer-logo.png" alt="footer-img"/>
    </div>
    <div class="address">
      <p>6801 N. CLASSEN BLVD., SUITE A | OKLAHOMA CITY, OKLAHOMA 73116-7207 | FAX: 405.848.2249 | 405.843.5060</p>

      <p>© 2015 B.D. EDDIE ENTERPRISES. ALL RIGHTS RESERVED.</p>
    </div>
  </div>
</footer>