<header id="site-header" class="site-header">
  <div class="site-container">
    <nav class="nav">
      <a class="btn-nav" href="#">Navigation Menu</a>
      <ul class="menu">
        <li><a href="#">HOME</a></li>
        <li><a href="#">AVAILABLE PROPERTIES</a></li>
        <li><a href="#">DEVELOPMENT PROJECTS</a></li>
        <li><a href="#">CONTACT</a></li>
      </ul>
    </nav>
    <div class="logo">
      <a href="BDEddie_Site_Homepage_v2.php"><img src="theme/images/logo.png" alt="logo"/>

        <h1>B.D. EDDIE ENTERPRISES</h1>
      </a>

      <div class="social-share">
        <a class="facebook" href="#facebook"></a>
        <a class="twitter" href="#twitter"></a>
        <a class="instagram" href="#instagram"></a>
      </div>
    </div>
  </div>
</header>