<header id="site-header" class="site-header">
  <div class="site-container">
    <nav class="nav">
      <a class="btn-nav" href="#"><span></span></a>
      <ul class="menu">
        <li><a href="#">HOME</a></li>
        <li><a href="#">AVAILABLE PROPERTIES</a></li>
        <li><a href="#">DEVELOPMENT PROJECTS</a></li>
        <li><a href="#">CONTACT</a></li>
      </ul>
    </nav>
    <div class="logo">
      <a href="BDEddie_Site_Homepage_v2.php"><img src="theme/images/logo.png" alt="logo"/>

        <h1>B.D. EDDIE ENTERPRISES</h1>
      </a>

      <div class="social-menu">
        <ul>
          <li class="facebook">
            <a  href="#facebook"></a>
          </li>
          <li class="twitter">
            <a  href="#twitter"></a>
          </li>
          <li class="instagram">
            <a  href="#instagram"></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>